In [1]:
import pandas as pd

df = pd.read_excel("data\Prestamos_Data_Alumnos_v5.xlsx")
df.head()

<>:3: SyntaxWarning: invalid escape sequence '\P'
<>:3: SyntaxWarning: invalid escape sequence '\P'
C:\Users\nahia\AppData\Local\Temp\ipykernel_17580\2509865948.py:3: SyntaxWarning: invalid escape sequence '\P'
  df = pd.read_excel("data\Prestamos_Data_Alumnos_v5.xlsx")

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Estudios,Tipo_Jornada_Laboral,Estado_Civil,Posesion_Hipoteca,Personas_Cargo,Proposito,Fiador,Impago,Prima
0,O77MPJ,26,19153.0,6973,706,9.0,1,19.05,36.0,0.10,Grado Universitario,Jornada completa,Soltero,0.0,1.0,Automóvil,1.0,1,130.83
1,6B4H6E,22,16000.0,10000,769,22.0,1,8.96,48.0,0.32,Escolar,Desempleado,Soltero,1.0,1.0,Vivienda,0.0,0,65.85
2,VKTUXP,33,38308.0,16474,699,70.0,3,14.07,36.0,0.20,Máster,Jornada completa,Casado,1.0,1.0,Vivienda,0.0,0,260.60
3,5P9OVL,51,51271.0,40770,812,309.0,1,12.66,12.0,0.36,Grado Universitario,Jornada completa,Casado,0.0,1.0,Vivienda,1.0,0,221.02
4,KG9CT9,34,56572.0,73978,763,86.0,1,13.91,60.0,0.55,Máster,Tiempo parcial,Soltero,0.0,0.0,Educación,0.0,0,800.00

In [2]:
df.info

<bound method DataFrame.info of             ID  Edad  Ingresos  Monto_Inicial  Scoring_Crediticio  \
0       O77MPJ    26   19153.0           6973                 706
1       6B4H6E    22   16000.0          10000                 769
2       VKTUXP    33   38308.0          16474                 699
3       5P9OVL    51   51271.0          40770                 812
4       KG9CT9    34   56572.0          73978                 763
...        ...   ...       ...            ...                 ...
510699  MY63P5    28   17390.0           5000                 744
510700  6903JQ    42   33486.0          33048                 760
510701  EPB8QX    64   40369.0          40000                 680
510702  R1QRKW    35   30915.0         130966                 739
510703  Q90VE4    28   25765.0           6515                 788

        Meses_Empleo  Num_Creditos  Ratio_Interes  Duracion  \
0                9.0             1          19.05      36.0
1               22.0             1           8.96      48.0
2               70.0             3          14.07      36.0
3              309.0             1          12.66      12.0
4               86.0             1          13.91      60.0
...              ...           ...            ...       ...
510699          92.0             3          16.12      12.0
510700         206.0             1           9.09      24.0
510701         447.0             2           7.75      12.0
510702         134.0             2          10.22      24.0
510703          20.0             1           8.29      24.0

        Ratio_Deuda_Ingresos             Estudios Tipo_Jornada_Laboral  \
0                       0.10  Grado Universitario     Jornada completa
1                       0.32              Escolar          Desempleado
2                       0.20               Máster     Jornada completa
3                       0.36  Grado Universitario     Jornada completa
4                       0.55               Máster       Tiempo parcial
...                      ...                  ...                  ...
510699                  0.10              Escolar          Desempleado
510700                  0.31  Grado Universitario             Autónomo
510701                  0.19              Escolar     Jornada completa
510702                  0.55              Escolar     Jornada completa
510703                  0.22  Grado Universitario       Tiempo parcial

       Estado_Civil  Posesion_Hipoteca  Personas_Cargo  Proposito  Fiador  \
0           Soltero                0.0             1.0  Automóvil     1.0
1           Soltero                1.0             1.0   Vivienda     0.0
2            Casado                1.0             1.0   Vivienda     0.0
3            Casado                0.0             1.0   Vivienda     1.0
4           Soltero                0.0             0.0  Educación     0.0
...             ...                ...             ...        ...     ...
510699      Soltero                0.0             0.0   Negocios     0.0
510700   Divorciado                0.0             0.0  Automóvil     0.0
510701       Casado                1.0             1.0   Negocios     1.0
510702       Casado                1.0             0.0  Educación     0.0
510703      Soltero                0.0             0.0   Negocios     0.0

        Impago   Prima
0            1  130.83
1            0   65.85
2            0  260.60
3            0  221.02
4            0  800.00
...        ...     ...
510699       0   26.80
510700       0  172.41
510701       1  207.42
510702       0  580.00
510703       0   17.01

[510704 rows x 19 columns]>

In [3]:
df.dtypes

ID                          str
Edad                      int64
Ingresos                float64
Monto_Inicial             int64
Scoring_Crediticio        int64
Meses_Empleo            float64
Num_Creditos              int64
Ratio_Interes           float64
Duracion                float64
Ratio_Deuda_Ingresos    float64
Estudios                    str
Tipo_Jornada_Laboral        str
Estado_Civil                str
Posesion_Hipoteca       float64
Personas_Cargo          float64
Proposito                   str
Fiador                  float64
Impago                    int64
Prima                   float64
dtype: object

In [4]:
# mirar cuantos duplicados hay
df['Proposito'].duplicated().value_counts()

Proposito
True     510698
False         6
Name: count, dtype: int64

In [5]:
# hacemos copia por si acaso
copia = df.copy()

In [6]:
copia.shape

(510704, 19)

In [7]:

#filtrar por vivienda => lo que nos toca
copia = copia[copia["Proposito"] == "Vivienda"]
copia.head()

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Estudios,Tipo_Jornada_Laboral,Estado_Civil,Posesion_Hipoteca,Personas_Cargo,Proposito,Fiador,Impago,Prima
1,6B4H6E,22,16000.0,10000,769,22.0,1,8.96,48.0,0.32,Escolar,Desempleado,Soltero,1.0,1.0,Vivienda,0.0,0,65.85
2,VKTUXP,33,38308.0,16474,699,70.0,3,14.07,36.0,0.20,Máster,Jornada completa,Casado,1.0,1.0,Vivienda,0.0,0,260.60
3,5P9OVL,51,51271.0,40770,812,309.0,1,12.66,12.0,0.36,Grado Universitario,Jornada completa,Casado,0.0,1.0,Vivienda,1.0,0,221.02
10,YL0W8G,30,31923.0,36707,813,43.0,1,8.96,24.0,0.32,Grado Universitario,Jornada completa,Casado,0.0,1.0,Vivienda,0.0,0,125.00
13,YP8WTV,28,27373.0,86981,765,60.0,2,10.07,48.0,0.55,Escolar,Jornada completa,Soltero,0.0,1.0,Vivienda,0.0,0,800.00

In [8]:

copia['Proposito'].value_counts()

Proposito
Vivienda    101899
Name: count, dtype: int64

In [9]:

# ver las filas de duplicados
duplicados=copia[copia.duplicated()]
duplicados

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Estudios,Tipo_Jornada_Laboral,Estado_Civil,Posesion_Hipoteca,Personas_Cargo,Proposito,Fiador,Impago,Prima
328169,AIJ783,52,46929.0,59359,683,427.0,2,14.76,36.0,0.36,Escolar,Jornada completa,Casado,1.0,1.0,Vivienda,0.0,0,760.00
425985,N3L8A6,22,18553.0,40000,805,20.0,3,13.04,60.0,0.55,Escolar,Jornada completa,Soltero,0.0,0.0,Vivienda,1.0,0,468.83
480472,TTGYVO,36,35293.0,40000,785,136.0,1,6.85,36.0,0.24,Grado Universitario,Jornada completa,Casado,0.0,1.0,Vivienda,0.0,0,292.69
501642,M60ASI,55,41241.0,49993,575,525.0,1,12.61,24.0,0.46,Escolar,Jornada completa,Soltero,0.0,0.0,Vivienda,0.0,0,580.00

In [10]:

id_dup=copia[copia['ID']=='AIJ783']
id_dup

,ID,Edad,Ingresos,Monto_Inicial,Scoring_Crediticio,Meses_Empleo,Num_Creditos,Ratio_Interes,Duracion,Ratio_Deuda_Ingresos,Estudios,Tipo_Jornada_Laboral,Estado_Civil,Posesion_Hipoteca,Personas_Cargo,Proposito,Fiador,Impago,Prima
225638,AIJ783,52,46929.0,59359,683,427.0,2,14.76,36.0,0.36,Escolar,Jornada completa,Casado,1.0,1.0,Vivienda,0.0,0,760.0
328169,AIJ783,52,46929.0,59359,683,427.0,2,14.76,36.0,0.36,Escolar,Jornada completa,Casado,1.0,1.0,Vivienda,0.0,0,760.0

In [11]:

#mirar valores nulos
copia.isna().sum()

ID                      0
Edad                    0
Ingresos                0
Monto_Inicial           0
Scoring_Crediticio      0
Meses_Empleo            0
Num_Creditos            0
Ratio_Interes           0
Duracion                1
Ratio_Deuda_Ingresos    1
Estudios                2
Tipo_Jornada_Laboral    1
Estado_Civil            0
Posesion_Hipoteca       2
Personas_Cargo          1
Proposito               0
Fiador                  1
Impago                  0
Prima                   1
dtype: int64

In [12]:

#sustituir nulos por las medias
media_duracion = copia['Duracion'].mean()

copia['Duracion']=copia['Duracion'].fillna(media_duracion)

copia['Duracion'] = copia['Duracion'].isna().sum()

copia["Estudios"]

1                     Escolar
2                      Máster
3         Grado Universitario
10        Grado Universitario
13                    Escolar
                 ...
510670    Grado Universitario
510671    Grado Universitario
510689              Doctorado
510691                 Máster
510694    Grado Universitario
Name: Estudios, Length: 101899, dtype: str